config/routes.rb
Rails.application.routes.draw do

  match "reports/:report", :to => 'dossier/reports#show', :as => :dossier_report

end

app/controllers/dossier/application_controller.rb
module Dossier
  class ApplicationController < ::ApplicationController
  end
end

app/controllers/dossier/reports_controller.rb
module Dossier
  class ReportsController < ApplicationController
    def show
      report = report_class.new(params[:options] || {})
      report.run

      respond_to do |format|
        format.html do
          begin
            render template: "dossier/reports/#{report_class.report_name}", locals: {report: report}
          rescue ActionView::MissingTemplate => e
            render template: 'dossier/reports/show', locals: {report: report}
          end
        end

        format.json do
          render :json => report.results.hashes
        end

        format.csv do
          set_content_disposition!
          self.response_body = StreamCSV.new(report.raw_results.arrays)
        end

        format.xls do
          set_content_disposition!
          self.response_body = Xls.new(report.raw_results.arrays)
        end
      end
    end

    private

    def report_class
      Dossier.name_to_class(params[:report])
    end

    def set_content_disposition!
      headers["Content-Disposition"] = %[attachment;filename=#{params[:report]}-report_#{Time.now.strftime('%m-%d-%Y_%H-%M-%S')}.#{params[:format]}]
    end

  end
end

app/helpers/dossier/application_helper.rb
module Dossier
  module ApplicationHelper
  end
end

app/views/dossier/reports/show.html.haml
%h1= report.class.name.titleize

= link_to 'Download CSV', dossier_report_path(format: 'csv', options: report.options, report: report.class.report_name), class: 'download-csv'

%table
  %thead
    %tr
      - report.results.headers.each do |header|
        %th= Dossier::Formatter.titleize(header)
  %tbody
    - report.results.body.each do |row|
      %tr
        - row.each do |value|
          %td= value

  - if report.results.footers.any?
    %tfoot
      - report.results.footers.each do |row|
        %tr
          - row.each do |value|
            %th= value